"""create macro_observations

Revision ID: 1df55e52506b
Revises:
Create Date: 2026-09-30 05:26:32.979883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1df55e52506b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "macro_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("series_id", sa.String(length=50), nullable=False),
        sa.Column("observation_date", sa.Date(), nullable=False),
        sa.Column("available_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("raw_value", sa.String(length=32), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "available_date >= observation_date",
            name="ck_macro_obs_available_after_observation",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "series_id",
            "observation_date",
            "available_date",
            name="uq_macro_obs_series_date_available",
        ),
    )
    op.create_index(
        "ix_macro_obs_series_available",
        "macro_observations",
        ["series_id", "available_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_macro_obs_series_available", table_name="macro_observations")
    op.drop_table("macro_observations")
    # ### end Alembic commands ###
